version: "3.8"  # Using version 3.8 for compatibility

services:
  application:
    image: ${IMAGE_NAME}  # Pulls the image from the specified IMAGE_NAME (e.g., your ECR registry)
    container_name: customer  # Names the container 'customer'
    ports:
      - "8080:8080"  # Exposes port 8080 on the host to port 8080 inside the container
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}  # AWS Access Key ID
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}  # AWS Secret Access Key
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}  # AWS Region (e.g., us-west-2)
      - MONGO_DB_URL=${MONGO_DB_URL}  # MongoDB connection URL
      - BUCKET_NAME=${BUCKET_NAME}  # Name of the S3 bucket
      
      # Airflow-related secrets
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}  # Airflow email
      - AIRFLOW_USERNAME=${AIRFLOW_USERNAME}  # Airflow username
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}  # Airflow password

    # Optionally, add a restart policy in case you want the container to restart on failure or stop
    restart: always  # Ensures the container restarts on failure or container stop
